/**
 * @brief Common data type
 */

#include "CommonDataType.h"

MAP_ENUM_STR(PLAYER_TYPE, DEF_PLAYER_TYPE)
MAP_ENUM_STR(STATE_TYPE, DEF_STATE_TYPE)
MAP_ENUM_STR(ITEM_TYPE, DEF_ITEM_TYPE)
MAP_ENUM_STR(BULLET_TYPE, DEF_BULLET_TYPE)
