// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Buckshot_Roulette_Project

#ifndef UI_MAIN_H
#define UI_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Main
extern void ui_Main_screen_init(void);
extern void ui_Main_screen_destroy(void);
extern void ui_event_Main(lv_event_t * e);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_Container1;
extern void ui_event_btnPlayer2Slot1(lv_event_t * e);
extern lv_obj_t * ui_btnPlayer2Slot1;
extern void ui_event_Image1(lv_event_t * e);
extern lv_obj_t * ui_Image1;
extern void ui_event_btnPlayer2Slot3(lv_event_t * e);
extern lv_obj_t * ui_btnPlayer2Slot3;
extern void ui_event_Image2(lv_event_t * e);
extern lv_obj_t * ui_Image2;
extern void ui_event_btnPlayer2Slot2(lv_event_t * e);
extern lv_obj_t * ui_btnPlayer2Slot2;
extern void ui_event_Image3(lv_event_t * e);
extern lv_obj_t * ui_Image3;
extern void ui_event_btnPlayer2Slot4(lv_event_t * e);
extern lv_obj_t * ui_btnPlayer2Slot4;
extern void ui_event_Image4(lv_event_t * e);
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Container2;
extern void ui_event_btnPlayer2Pick(lv_event_t * e);
extern lv_obj_t * ui_btnPlayer2Pick;
extern void ui_event_btnPlayer2Slot5(lv_event_t * e);
extern lv_obj_t * ui_btnPlayer2Slot5;
extern void ui_event_Image6(lv_event_t * e);
extern lv_obj_t * ui_Image6;
extern void ui_event_btnPlayer2Slot7(lv_event_t * e);
extern lv_obj_t * ui_btnPlayer2Slot7;
extern void ui_event_Image7(lv_event_t * e);
extern lv_obj_t * ui_Image7;
extern void ui_event_btnPlayer2Slot6(lv_event_t * e);
extern lv_obj_t * ui_btnPlayer2Slot6;
extern void ui_event_Image8(lv_event_t * e);
extern lv_obj_t * ui_Image8;
extern void ui_event_btnPlayer2Slot8(lv_event_t * e);
extern lv_obj_t * ui_btnPlayer2Slot8;
extern void ui_event_Image9(lv_event_t * e);
extern lv_obj_t * ui_Image9;
extern void ui_event_imgPlayer2Block(lv_event_t * e);
extern lv_obj_t * ui_imgPlayer2Block;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Container13;
extern lv_obj_t * ui_lblPlayer2ChargeBack1;
extern lv_obj_t * ui_lblPlayer2ChargeBack2;
extern lv_obj_t * ui_lblPlayer2ChargeBack3;
extern lv_obj_t * ui_lblPlayer2ChargeBack4;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_lblPlayer2Charge1;
extern lv_obj_t * ui_lblPlayer2Charge2;
extern lv_obj_t * ui_lblPlayer2Charge3;
extern lv_obj_t * ui_lblPlayer2Charge4;
extern lv_obj_t * ui_Container15;
extern lv_obj_t * ui_cbRound1;
extern lv_obj_t * ui_cbRound2;
extern lv_obj_t * ui_cbRound3;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_lblPlayer1Charge1;
extern lv_obj_t * ui_lblPlayer1Charge2;
extern lv_obj_t * ui_lblPlayer1Charge3;
extern lv_obj_t * ui_lblPlayer1Charge4;
extern lv_obj_t * ui_Container14;
extern lv_obj_t * ui_lblPlayer1ChargeBack1;
extern lv_obj_t * ui_lblPlayer1ChargeBack2;
extern lv_obj_t * ui_lblPlayer1ChargeBack3;
extern lv_obj_t * ui_lblPlayer1ChargeBack4;
extern void ui_event_imgbtnShotgunInTable(lv_event_t * e);
extern lv_obj_t * ui_imgbtnShotgunInTable;
extern lv_obj_t * ui_imgTrashBullet;
extern lv_obj_t * ui_imgEjectedBullet;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_imgBullet1;
extern lv_obj_t * ui_imgBullet2;
extern lv_obj_t * ui_imgBullet3;
extern lv_obj_t * ui_imgBullet4;
extern lv_obj_t * ui_imgBullet5;
extern lv_obj_t * ui_imgBullet6;
extern lv_obj_t * ui_imgBullet7;
extern lv_obj_t * ui_imgBullet8;
extern lv_obj_t * ui_imgBulletBoxCover;
extern void ui_event_sldBrightness(lv_event_t * e);
extern lv_obj_t * ui_sldBrightness;
extern lv_obj_t * ui_Container10;
extern void ui_event_btnPlayer1Slot1(lv_event_t * e);
extern lv_obj_t * ui_btnPlayer1Slot1;
extern void ui_event_Image11(lv_event_t * e);
extern lv_obj_t * ui_Image11;
extern void ui_event_btnPlayer1Slot3(lv_event_t * e);
extern lv_obj_t * ui_btnPlayer1Slot3;
extern void ui_event_Image12(lv_event_t * e);
extern lv_obj_t * ui_Image12;
extern void ui_event_btnPlayer1Slot2(lv_event_t * e);
extern lv_obj_t * ui_btnPlayer1Slot2;
extern void ui_event_Image13(lv_event_t * e);
extern lv_obj_t * ui_Image13;
extern void ui_event_btnPlayer1Slot4(lv_event_t * e);
extern lv_obj_t * ui_btnPlayer1Slot4;
extern void ui_event_Image14(lv_event_t * e);
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_Container11;
extern void ui_event_btnPlayer1Pick(lv_event_t * e);
extern lv_obj_t * ui_btnPlayer1Pick;
extern void ui_event_btnPlayer1Slot5(lv_event_t * e);
extern lv_obj_t * ui_btnPlayer1Slot5;
extern void ui_event_Image15(lv_event_t * e);
extern lv_obj_t * ui_Image15;
extern void ui_event_btnPlayer1Slot7(lv_event_t * e);
extern lv_obj_t * ui_btnPlayer1Slot7;
extern void ui_event_Image16(lv_event_t * e);
extern lv_obj_t * ui_Image16;
extern void ui_event_btnPlayer1Slot6(lv_event_t * e);
extern lv_obj_t * ui_btnPlayer1Slot6;
extern void ui_event_Image26(lv_event_t * e);
extern lv_obj_t * ui_Image26;
extern void ui_event_btnPlayer1Slot8(lv_event_t * e);
extern lv_obj_t * ui_btnPlayer1Slot8;
extern void ui_event_Image27(lv_event_t * e);
extern lv_obj_t * ui_Image27;
extern void ui_event_imgPlayer1Block(lv_event_t * e);
extern lv_obj_t * ui_imgPlayer1Block;
extern lv_obj_t * ui_wndShotgunConfirm;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label9;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_wndShotgunShotEffect;
extern void ui_event_imgShotgunInside(lv_event_t * e);
extern lv_obj_t * ui_imgShotgunInside;
extern lv_obj_t * ui_imgShotgunBullet;
extern lv_obj_t * ui_imgShotgunBullet1;
extern lv_obj_t * ui_imgShotgunInHand;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

