// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Buckshot_Roulette_Project

#ifndef _BUCKSHOT_ROULETTE_PROJECT_UI_H
#define _BUCKSHOT_ROULETTE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Start.h"
#include "screens/ui_Main.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_metal_table_png);    // assets/metal_table.png
LV_IMG_DECLARE(ui_img_empty_png);    // assets/Empty.png
LV_IMG_DECLARE(ui_img_picking_png);    // assets/picking.png
LV_IMG_DECLARE(ui_img_block_png);    // assets/block.png
LV_IMG_DECLARE(ui_img_chargeback_png);    // assets/ChargeBack.png
LV_IMG_DECLARE(ui_img_charge_png);    // assets/Charge.png
LV_IMG_DECLARE(ui_img_shotgun_png);    // assets/Shotgun.png
LV_IMG_DECLARE(ui_img_shotgun_block_png);    // assets/shotgun_block.png
LV_IMG_DECLARE(ui_img_live_png);    // assets/Live.png
LV_IMG_DECLARE(ui_img_metal_bullet_box_png);    // assets/metal_bullet_box.png
LV_IMG_DECLARE(ui_img_empty_bullet_png);    // assets/empty_bullet.png
LV_IMG_DECLARE(ui_img_hide_png);    // assets/hide.png
LV_IMG_DECLARE(ui_img_adrenaline_png);    // assets/Adrenaline.png
LV_IMG_DECLARE(ui_img_beer_png);    // assets/Beer.png
LV_IMG_DECLARE(ui_img_blank_png);    // assets/Blank.png
LV_IMG_DECLARE(ui_img_burnerphone_png);    // assets/BurnerPhone.png
LV_IMG_DECLARE(ui_img_cigarette_png);    // assets/Cigarette.png
LV_IMG_DECLARE(ui_img_expiredmedicine_png);    // assets/ExpiredMedicine.png
LV_IMG_DECLARE(ui_img_handcuffs_png);    // assets/Handcuffs.png
LV_IMG_DECLARE(ui_img_handsaw_png);    // assets/Handsaw.png
LV_IMG_DECLARE(ui_img_inverter_png);    // assets/Inverter.png
LV_IMG_DECLARE(ui_img_load_png);    // assets/Load.png
LV_IMG_DECLARE(ui_img_magnifyingglass_png);    // assets/MagnifyingGlass.png
LV_IMG_DECLARE(ui_img_metal_turntable_png);    // assets/metal_turntable.png
LV_IMG_DECLARE(ui_img_shotgunback_png);    // assets/ShotgunBack.png
LV_IMG_DECLARE(ui_img_shotguncut_png);    // assets/ShotgunCut.png
LV_IMG_DECLARE(ui_img_shotgun_in_hand_png);    // assets/shotgun_in_hand.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
