// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Buckshot_Roulette_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Start_OnLoaded(lv_event_t * e);
void Main_OnLoaded(lv_event_t * e);
void OnItemSelect(lv_event_t * e);
void OnItemPick(lv_event_t * e);
void OnShotgunSelect(lv_event_t * e);
void OnBrightnessChange(lv_event_t * e);
void OnShotgunShot(lv_event_t * e);
void OnShotgunInsideClick(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
