// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifdef _WIN64
#include <iostream>
#endif
#include <algorithm>
#include "ui.h"
#include "../CommonData.h"
#include "../CommonLibrary.h"
#include "../CommonService.h"
#include "../Entity.h"

// Entity
static player::player_info_t* Player = nullptr;
static shotgun::shotgun_info_t Shotgun = { };

// Internal variable
static std::unordered_map<ITEM_TYPE, std::pair<lv_img_dsc_t, std::function<void(player::player_info_t::player_slot_button_t&)>>> mapItemImg;
static std::vector<std::tuple<ITEM_TYPE, lv_img_dsc_t, lv_obj_t*>> listItemCardButton;
static ITEM_TYPE currentPickItem = ITEM_TYPE::MIN;
static bool itemUsingState = false;
static ITEM_TYPE itemUsingType = ITEM_TYPE::MIN;
static uint64_t lastShotgunTime = 0;
static PLAYER_TYPE latestPlayer = PLAYER_TYPE::PLAYER1;

#pragma region Internal_functions
static void ResetPlayerTable()
{
    for (auto& player : player::listPlayer)
    {
        player.Disable();
    }

    Shotgun.Disable();
}

static void ShowEjectedBullet()
{
    debug_println("Eject bullet");

    lv_obj_remove_flag(ui_imgEjectedBullet, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_imgTrashBullet, LV_OBJ_FLAG_HIDDEN);
}

static void ShowTrashBullet()
{
    debug_println("Trash bullet");

    lv_obj_remove_flag(ui_imgTrashBullet, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_imgEjectedBullet, LV_OBJ_FLAG_HIDDEN);
}

static void HideBulletInTable()
{
    debug_println("Hide bullet");

    lv_obj_add_flag(ui_imgTrashBullet, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_imgEjectedBullet, LV_OBJ_FLAG_HIDDEN);
}
#pragma endregion

#include "FSM.h"
#include "Effect.h"

void Init()
{
    // Brightness
    Brightness.SetValue(100);
    lv_slider_set_value(ui_sldBrightness, Brightness.GetValue(), LV_ANIM_OFF);

    // Init image map
    mapItemImg = {
        { ITEM_TYPE::BEER           , { ui_img_beer_png           , EFFECT_FUNCTION_CALLBACK(BEER)            } },
        { ITEM_TYPE::BURNERPHONE    , { ui_img_burnerphone_png    , EFFECT_FUNCTION_CALLBACK(BURNERPHONE)     } },
        { ITEM_TYPE::CIGARETTE      , { ui_img_cigarette_png      , EFFECT_FUNCTION_CALLBACK(CIGARETTE)       } },
        { ITEM_TYPE::EXPIREDMEDICINE, { ui_img_expiredmedicine_png, EFFECT_FUNCTION_CALLBACK(EXPIREDMEDICINE) } },
        { ITEM_TYPE::HANDCUFFS      , { ui_img_handcuffs_png      , EFFECT_FUNCTION_CALLBACK(HANDCUFFS)       } },
        { ITEM_TYPE::HANDSAW        , { ui_img_handsaw_png        , EFFECT_FUNCTION_CALLBACK(HANDSAW)         } },
        { ITEM_TYPE::INVERTER       , { ui_img_inverter_png       , EFFECT_FUNCTION_CALLBACK(INVERTER)        } },
        { ITEM_TYPE::MAGNIFYINGGLASS, { ui_img_magnifyingglass_png, EFFECT_FUNCTION_CALLBACK(MAGNIFYINGGLASS) } },
        { ITEM_TYPE::ADRENALINE     , { ui_img_adrenaline_png     , EFFECT_FUNCTION_CALLBACK(ADRENALINE)      } },
    };

    // Init card info button
    listItemCardButton = {
        { ITEM_TYPE::BEER           , ui_img_beer_png           , ui_btnCard1 },
        { ITEM_TYPE::BURNERPHONE    , ui_img_burnerphone_png    , ui_btnCard2 },
        { ITEM_TYPE::CIGARETTE      , ui_img_cigarette_png      , ui_btnCard3 },
        { ITEM_TYPE::EXPIREDMEDICINE, ui_img_expiredmedicine_png, ui_btnCard4 },
        { ITEM_TYPE::HANDCUFFS      , ui_img_handcuffs_png      , ui_btnCard5 },
        { ITEM_TYPE::HANDSAW        , ui_img_handsaw_png        , ui_btnCard6 },
        { ITEM_TYPE::INVERTER       , ui_img_inverter_png       , ui_btnCard7 },
        { ITEM_TYPE::MAGNIFYINGGLASS, ui_img_magnifyingglass_png, ui_btnCard8 },
        { ITEM_TYPE::ADRENALINE     , ui_img_adrenaline_png     , ui_btnCard9 },
        { ITEM_TYPE::BLANK          , ui_img_cblank_png         , ui_btnCard10 },
        { ITEM_TYPE::LIVE           , ui_img_clive_png          , ui_btnCard11 },
        { ITEM_TYPE::NORMAL_CHARGE  , ui_img_cchargefront_png   , ui_btnCard12 },
        { ITEM_TYPE::FADED_CHARGE   , ui_img_cchargeback_png    , ui_btnCard13 },
    };

    // Init shotgun
    Shotgun.objInTable = ui_imgbtnShotgunInTable;
    Shotgun.objInside = ui_imgbtnShotgunInside;
    Shotgun.objHand = ui_imgShotgunInHand;
    Shotgun.objEffect = ui_wndShotgunShotEffect;
    Shotgun.objWndConfirm = ui_wndShotgunConfirm;
    Shotgun.objTrashBullet = ui_imgTrashBullet;
    Shotgun.mapBulletImg = {
        { BULLET_TYPE::MIN, ui_img_empty_bullet_png },
        { BULLET_TYPE::LIVE, ui_img_live_png },
        { BULLET_TYPE::BLANK, ui_img_blank_png },
    };
    Shotgun.listBulletImg = {
        ui_imgBullet1,
        ui_imgBullet2,
        ui_imgBullet3,
        ui_imgBullet4,
        ui_imgBullet5,
        ui_imgBullet6,
        ui_imgBullet7,
        ui_imgBullet8,
    };

    // Init player #1
    player::player_info_t player1 = { };
    player1.type = PLAYER_TYPE::PLAYER1;
    player1.pickButton = ui_btnPlayer1Pick;
    player1.listButtonInfo = {
        { PLAYER_TYPE::MIN, ITEM_TYPE::MIN, ui_btnPlayer1Slot1, ui_imgbtnPlayer1Slot1, { 0 } },
        { PLAYER_TYPE::MIN, ITEM_TYPE::MIN, ui_btnPlayer1Slot2, ui_imgbtnPlayer1Slot2, { 0 } },
        { PLAYER_TYPE::MIN, ITEM_TYPE::MIN, ui_btnPlayer1Slot3, ui_imgbtnPlayer1Slot3, { 0 } },
        { PLAYER_TYPE::MIN, ITEM_TYPE::MIN, ui_btnPlayer1Slot4, ui_imgbtnPlayer1Slot4, { 0 } },
        { PLAYER_TYPE::MIN, ITEM_TYPE::MIN, ui_btnPlayer1Slot5, ui_imgbtnPlayer1Slot5, { 0 } },
        { PLAYER_TYPE::MIN, ITEM_TYPE::MIN, ui_btnPlayer1Slot6, ui_imgbtnPlayer1Slot6, { 0 } },
        { PLAYER_TYPE::MIN, ITEM_TYPE::MIN, ui_btnPlayer1Slot7, ui_imgbtnPlayer1Slot7, { 0 } },
        { PLAYER_TYPE::MIN, ITEM_TYPE::MIN, ui_btnPlayer1Slot8, ui_imgbtnPlayer1Slot8, { 0 } },
    };
    player1.listHPLevel1 = {
        ui_lblPlayer1ChargeBack1,
        ui_lblPlayer1ChargeBack2,
        ui_lblPlayer1ChargeBack3,
        ui_lblPlayer1ChargeBack4,
    };
    player1.listHPLevel2 = {
        ui_lblPlayer1Charge1,
        ui_lblPlayer1Charge2,
        ui_lblPlayer1Charge3,
        ui_lblPlayer1Charge4,
    };
    player1.hpLevel1 = MAX_HP;
    player1.hpLevel2 = MAX_HP;
    player1.angle = PLAYER1_ANGLE;

    // Init player #2
    player::player_info_t player2 = { };
    player2.type = PLAYER_TYPE::PLAYER2;
    player2.pickButton = ui_btnPlayer2Pick;
    player2.listButtonInfo = {
        { PLAYER_TYPE::MIN, ITEM_TYPE::MIN, ui_btnPlayer2Slot1, ui_imgbtnPlayer2Slot1, { 0 } },
        { PLAYER_TYPE::MIN, ITEM_TYPE::MIN, ui_btnPlayer2Slot2, ui_imgbtnPlayer2Slot2, { 0 } },
        { PLAYER_TYPE::MIN, ITEM_TYPE::MIN, ui_btnPlayer2Slot3, ui_imgbtnPlayer2Slot3, { 0 } },
        { PLAYER_TYPE::MIN, ITEM_TYPE::MIN, ui_btnPlayer2Slot4, ui_imgbtnPlayer2Slot4, { 0 } },
        { PLAYER_TYPE::MIN, ITEM_TYPE::MIN, ui_btnPlayer2Slot5, ui_imgbtnPlayer2Slot5, { 0 } },
        { PLAYER_TYPE::MIN, ITEM_TYPE::MIN, ui_btnPlayer2Slot6, ui_imgbtnPlayer2Slot6, { 0 } },
        { PLAYER_TYPE::MIN, ITEM_TYPE::MIN, ui_btnPlayer2Slot7, ui_imgbtnPlayer2Slot7, { 0 } },
        { PLAYER_TYPE::MIN, ITEM_TYPE::MIN, ui_btnPlayer2Slot8, ui_imgbtnPlayer2Slot8, { 0 } },
    };
    player2.listHPLevel1 = {
        ui_lblPlayer2ChargeBack1,
        ui_lblPlayer2ChargeBack2,
        ui_lblPlayer2ChargeBack3,
        ui_lblPlayer2ChargeBack4,
    };
    player2.listHPLevel2 = {
        ui_lblPlayer2Charge1,
        ui_lblPlayer2Charge2,
        ui_lblPlayer2Charge3,
        ui_lblPlayer2Charge4,
    };
    player2.hpLevel1 = MAX_HP;
    player2.hpLevel2 = MAX_HP;
    player2.angle = PLAYER2_ANGLE;

    // Add player list
    player::listPlayer = { player1, player2 };

    // Init state
    CurrentState.SetValue(STATE_TYPE::STARTUP);
}

void AutoUpdate()
{
#ifdef _WIN64 // Debug only
    // Debug change player
    if (debug_data::CurrentPlayer.GetState())
    {
        for (auto& player : player::listPlayer)
        {
            if (player.type == debug_data::CurrentPlayer.GetValue())
            {
                Player = &player;
                break;
            }
        }
    }
    if (debug_data::PlayerHP.GetState())
    {
        auto info = debug_data::PlayerHP.GetValue();

        for (auto& player : player::listPlayer)
        {
            if (player.type == std::get<0>(info))
            {
                if (std::get<1>(info) == 1)
                {
                    player.hpLevel1 = std::get<2>(info);
                }
                else if (std::get<1>(info) == 2)
                {
                    player.hpLevel2 = std::get<2>(info);
                }

                FSMTransit(STATE_TYPE::UPDATE_HP);

                break;
            }
        }
    }
    if (debug_data::SpecialCommand.GetState())
    {
        auto command = debug_data::SpecialCommand.GetValue();

        if (command == "bulletbox")
        {
            std::queue<BULLET_TYPE> tempQueue = Shotgun.queueBullet;

            debug_println("Bullet box:");
            while (!tempQueue.empty())
            {
                debug_println(map_BULLET_TYPE[tempQueue.front()]);
                tempQueue.pop();
            }
        }
        else if (command == "gettotalitem")
        {
            for (const auto& iPlayer : player::listPlayer)
            {
                debug_println(map_PLAYER_TYPE[iPlayer.type] + ": " + std::to_string(iPlayer.totalItemCount));
            }
        }

        debug_data::SpecialCommand.SetValue("");
    }
#endif

    // Pre-block check
    if (GuiBlockState.GetState())
    {
        if (GuiBlockState.GetValue())
        {
            debug_println("GUI block");

            lv_obj_remove_flag(ui_wndBlock, LV_OBJ_FLAG_HIDDEN);
        }
        else
        {
            debug_println("GUI unblock");

            lv_obj_add_flag(ui_wndBlock, LV_OBJ_FLAG_HIDDEN);
        }
    }

    FSM();

    // Post-block check
    if (GuiBlockState.GetState())
    {
        if (GuiBlockState.GetValue())
        {
            debug_println("GUI block");

            lv_obj_remove_flag(ui_wndBlock, LV_OBJ_FLAG_HIDDEN);
        }
        else
        {
            debug_println("GUI unblock");

            lv_obj_add_flag(ui_wndBlock, LV_OBJ_FLAG_HIDDEN);
        }
    }
}

void OnBrightnessChange(lv_event_t* e)
{
    Brightness.SetValue(lv_slider_get_value(ui_sldBrightness));
}

#pragma region Screen_events
void Start_OnLoaded(lv_event_t* e)
{

}

void Main_OnLoaded(lv_event_t* e)
{

}

void Info_OnLoaded(lv_event_t* e)
{
    e->current_target = std::get<2>(listItemCardButton[0]);

    OnCardSelect(e);
}
#pragma endregion

#pragma region Component_events
void OnShotgunShot(lv_event_t* e)
{
    auto currentButton = (lv_obj_t*)(e->current_target);

    if (currentButton == ui_btnPlayer1Confirm)
    {
        Shotgun.targetPlayer = Player;
    }
    else if (currentButton == ui_btnPlayer2Confirm)
    {
        Shotgun.targetPlayer = &player::NextPlayer(*Player);
    }

    debug_println("Confirm target: " + map_PLAYER_TYPE[Shotgun.targetPlayer->type]);

    lastShotgunTime = MILLISEC_GET;

    Shotgun.state = 0;

    lv_obj_add_state(ui_btnPlayer1Confirm, LV_STATE_DISABLED);
    lv_obj_add_state(ui_btnPlayer2Confirm, LV_STATE_DISABLED);

    FSMTransit(STATE_TYPE::SHOTGUN_SHOT);
}

void OnItemSelect(lv_event_t* e)
{
    if (Player)
    {
        // Get current slot button
        auto currentButton = (lv_obj_t*)(e->current_target);

        if (CurrentState.GetValue() == STATE_TYPE::PLAYER_ITEM_ARRANGE)
        {
            auto resultButtonInfo = std::find_if(Player->listButtonInfo.begin(), Player->listButtonInfo.end(),
                [currentButton](const decltype(Player->listButtonInfo.front())& item) {
                    // Button has no assigned image
                    return ((item.button == currentButton) && (item.image.data_size == 0));
                });

            if (resultButtonInfo != Player->listButtonInfo.end())
            {
                auto& buttonInfo = (*resultButtonInfo); // Get button info
                auto imgCardReview = lv_image_get_src(ui_imgCardReview); // Get image from card review

                debug_println("Pick: " + map_ITEM_TYPE[currentPickItem]);

                // Assign button
                buttonInfo.Assign(Player->type, currentPickItem, imgCardReview);

                // Update item count
                Player->pickItemCount++;
                Player->totalItemCount++;

                // Hide card review
                lv_obj_add_flag(ui_imgCardReview, LV_OBJ_FLAG_HIDDEN);

                FSMTransit(STATE_TYPE::PICK);
            }
        }
        else if (CurrentState.GetValue() == STATE_TYPE::ACTION_ITEM)
        {
            if (itemUsingType == ITEM_TYPE::ADRENALINE)
            {
                for (auto& iPlayer : player::listPlayer)
                {
                    auto resultButtonInfo = std::find_if(iPlayer.listButtonInfo.begin(), iPlayer.listButtonInfo.end(),
                        [currentButton](const decltype(iPlayer.listButtonInfo.front())& item) {
                            // Button has assigned image
                            return ((item.button == currentButton) && (item.image.data_size > 0));
                        });

                    if (resultButtonInfo != iPlayer.listButtonInfo.end())
                    {
                        auto& buttonInfo = (*resultButtonInfo); // Get button info

                        if ((buttonInfo.playerType != Player->type) && (buttonInfo.itemType != ITEM_TYPE::ADRENALINE) && (!itemUsingState))
                        {
                            debug_println("Use: " + map_ITEM_TYPE[buttonInfo.itemType]);
                            debug_println("From: " + map_PLAYER_TYPE[buttonInfo.playerType]);

                            itemUsingState = true; // Block other action
                            itemUsingType = buttonInfo.itemType;
                            mapItemImg[buttonInfo.itemType].second(buttonInfo); // Call item effect

                            iPlayer.totalItemCount--;

                            player::DisableAllPlayerTableExcept(*Player);
                        }

                        break;
                    }
                }
            }
            else
            {
                auto resultButtonInfo = std::find_if(Player->listButtonInfo.begin(), Player->listButtonInfo.end(),
                    [currentButton](const decltype(Player->listButtonInfo.front())& item) {
                        // Button has assigned image
                        return ((item.button == currentButton) && (item.image.data_size > 0));
                    });

                if (resultButtonInfo != Player->listButtonInfo.end())
                {
                    auto& buttonInfo = (*resultButtonInfo); // Get button info

                    if (!itemUsingState)
                    {
                        debug_println("Use: " + map_ITEM_TYPE[buttonInfo.itemType]);

                        itemUsingType = buttonInfo.itemType;
                        itemUsingState = true; // Block other action
                        mapItemImg[buttonInfo.itemType].second(buttonInfo); // Call item effect

                        Player->totalItemCount--;
                    }
                }
            }
        }
    }
}

void OnShotgunSelect(lv_event_t* e)
{
    if (CurrentState.GetValue() == STATE_TYPE::LOAD_SHELL)
    {
        debug_println("Shell loaded");

        // Show bullet box cover
        lv_obj_remove_flag(ui_imgBulletBoxCover, LV_OBJ_FLAG_HIDDEN);

        // Hide message
        lv_obj_add_flag(ui_lblCardMessage, LV_OBJ_FLAG_HIDDEN);

        FSMTransit(STATE_TYPE::ACTION_TURN);
    }
    else if (CurrentState.GetValue() == STATE_TYPE::ACTION_ITEM)
    {
        debug_println("Show shotgun in hand");

        lv_obj_remove_state(ui_btnPlayer1Confirm, LV_STATE_DISABLED);
        lv_obj_remove_state(ui_btnPlayer2Confirm, LV_STATE_DISABLED);

        Shotgun.ShowInHand(*Player);
    }
}

void OnItemPick(lv_event_t* e)
{
#ifdef _WIN64
    if ((uint8_t)debug_data::CurrentItemType.GetValue() > 0)
    {
        currentPickItem = debug_data::CurrentItemType.GetValue();
    }
    else
    {
        currentPickItem = RandomRangeEnum(ITEM_TYPE::MIN, ITEM_TYPE::MAX);
    }

    debug_data::CurrentItemType.SetValue(ITEM_TYPE::MIN);
#else
    currentPickItem = RandomRangeEnum(ITEM_TYPE::MIN, ITEM_TYPE::MAX);
#endif

    // Show and set image to card review
    lv_obj_remove_flag(ui_imgCardReview, LV_OBJ_FLAG_HIDDEN);
    lv_image_set_src(ui_imgCardReview, &mapItemImg[currentPickItem].first);

    if (Player)
    {
        Player->DisablePickButton();

        if ((Player->pickItemCount == MAX_PICK_ITEM_PER_ROUND) || (Player->totalItemCount == MAX_ITEM_NUM))
        {
            ResetPlayerTable();

            // Show message
            lv_obj_remove_flag(ui_lblCardMessage, LV_OBJ_FLAG_HIDDEN);

            // Set message
            if (Player->totalItemCount == MAX_ITEM_NUM)
            {
                lv_label_set_text(ui_lblCardMessage, MSG_OUT_OF_SPACE);
            }
            else if (Player->pickItemCount == MAX_PICK_ITEM_PER_ROUND)
            {
                lv_label_set_text(ui_lblCardMessage, MSG_END_TURN);
            }

            // Reset pick item count, keep total count
            Player->pickItemCount = 0;
            Player->isPickComplete = true;

            // Show delayed message
            DelayCallback(MAKE_DELAY_CB{
                // Hide card review
                lv_obj_add_flag(ui_imgCardReview, LV_OBJ_FLAG_HIDDEN);

            // Hide message
            lv_obj_add_flag(ui_lblCardMessage, LV_OBJ_FLAG_HIDDEN);

            FSMTransit(STATE_TYPE::PLAYER_NEXT);
                }, nullptr, WAIT_TIME);
        }
        else
        {
            FSMTransit(STATE_TYPE::PLAYER_ITEM_ARRANGE);
        }
    }
}

void OnShotgunInside(lv_event_t* e)
{
    auto eventCode = lv_event_get_code(e);

    if (eventCode == LV_EVENT_PRESSED)
    {
        // Show first bullet
        lv_image_set_src(ui_imgShotgunBullet, &Shotgun.mapBulletImg[Shotgun.queueBullet.front()]);
    }
    else
    {
        // Reset bullet slot
        lv_image_set_src(ui_imgShotgunBullet, &Shotgun.mapBulletImg[BULLET_TYPE::MIN]);

        // Hide shotgun inside
        lv_obj_add_flag(Shotgun.objInside, LV_OBJ_FLAG_HIDDEN);

        itemUsingState = false;
    }
}

void OnCardSelect(lv_event_t* e)
{
    auto currentButton = (lv_obj_t*)(e->current_target);

    auto resultButtonInfo = std::find_if(listItemCardButton.begin(), listItemCardButton.end(),
        [currentButton](const decltype(listItemCardButton.front())& item) {
            return (std::get<2>(item) == currentButton);
        });

    if (resultButtonInfo != listItemCardButton.end())
    {
        const auto& item = *resultButtonInfo;

        // Set text
        lv_label_set_text(ui_lblCardInfoTitle, mapCardInfoName[std::get<0>(item)].c_str());
        lv_label_set_text(ui_lblUsageInfo, JoinString("\n", mapCardInfoDesc[std::get<0>(item)].usageLines).c_str());
        lv_label_set_text(ui_lblStrategyInfo, JoinString("\n", mapCardInfoDesc[std::get<0>(item)].strategyLines).c_str());

        // Set image
        lv_image_set_src(ui_imgInfoCardReview, &std::get<1>(item));
    }
}

void OnButtonHelp(lv_event_t* e)
{
    if (e->current_target == ui_btnPlayer1Help)
    {
        lv_obj_set_style_transform_rotation(ui_wndInfo, player::listPlayer[0].angle, LV_PART_MAIN | LV_STATE_DEFAULT);
    }
    else if (e->current_target == ui_btnPlayer2Help)
    {
        lv_obj_set_style_transform_rotation(ui_wndInfo, player::listPlayer[1].angle, LV_PART_MAIN | LV_STATE_DEFAULT);
    }

    _ui_screen_change(&ui_Info, LV_SCR_LOAD_ANIM_MOVE_LEFT, 100, 0, &ui_Info_screen_init);
}
#pragma endregion
